name       : perl-pod-simple
version    : '3.45'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/K/KH/KHW/Pod-Simple-3.45.tar.gz : 8483bb95cd3e4307d66def092a3779f843af772482bfdc024e3e00d0c4db0cfa
homepage   : https://metacpan.org/pod/Pod::Simple
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod::Simple - framework for parsing Pod
description: |
    Pod::Simple is a Perl library for parsing text in the Pod ("plain old documentation") markup language that is typically used for writing documentation for Perl and for Perl modules.
builddeps  :
    - perl-test-deep        # tests
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
