name       : perl-pod-simple
version    : '3.40'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/K/KH/KHW/Pod-Simple-3.40.tar.gz : 063a8cb9d8abd84fd64c3e9581addf96a6b0f77a2048a1846c3a6b14269a040d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod formatters can use Pod::Simple to parse Pod documents and render them into plain text, HTML, or any number of other formats
description: |
    Pod::Simple is a Perl library for parsing text in the Pod ("plain old documentation") markup language that is typically used for writing documentation for Perl and for Perl modules.
builddeps  :
    - perl-test-deep        # tests
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
