name       : perl-pod-simple
version    : 3.35
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/K/KH/KHW/Pod-Simple-3.35.tar.gz : 99a120ccd2146e8b352b7778f7ae021f7525419764eb05b8125400b6560ce13d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Pod formatters can use Pod::Simple to parse Pod documents and render them into plain text, HTML, or any number of other formats.
description: |
    Pod::Simple is a Perl library for parsing text in the Pod ("plain old documentation") markup language that is typically used for writing documentation for Perl and for Perl modules.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
